version: "3.8"
services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
    volumes:
      - ./data:/data
      - ./mods:/mods
    tty: true
    stdin_open: true

