app = "mc-mod-server"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory   = "1gb"
  cpu_kind = "shared"
  cpus     = 1

[[services]]
  protocol      = "tcp"
  internal_port = 25565

  [[services.ports]]
    port = 25565

